# Generated by Django 5.0.3 on 2024-05-03 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_customuser_favorite_customuser_favorite_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('common_genre', models.CharField(max_length=100)),
                ('artist', models.ForeignKey(help_text='Enter album artist here', on_delete=django.db.models.deletion.CASCADE, to='catalog.album')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(help_text='Select the album this song belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.album'),
        ),
    ]
