# Generated by Django 5.0.3 on 2024-05-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(help_text='Select the album this song belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.album'),
        ),
    ]
