# Generated by Django 5.0.3 on 2024-05-03 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_album_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(help_text='Select album artist', on_delete=django.db.models.deletion.CASCADE, to='catalog.artist'),
        ),
    ]
